spring:
  datasource:
    username: ${POSTGRE_USER}
    password: ${POSTGRE_PASS}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:2345/events

  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true

  liquibase:
    enabled: true
    change-log: db.changelog/db.changelog-master.xml