name: MyWorkflow
env:
  APPLICATION_NAME: "SportEventManagementSystem"
  COMMIT_INFO: "SportEventManagementSystem: commit ${{ github.sha }}"

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Run Maven test
      run: mvn test --file pom.xml
      
  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Show commit sha
        run: "${{ env.COMMIT_INFO }}"
      - name: Run Maven Build
        run: mvn clean install --file pom.xml
